" Name:         Cobalt3 
" Description:  My color scheme
" Author:       Alvaro Muñoz <alvaro@pwntester.com>
" Maintainer:   Alvaro Muñoz <alvaro@pwntester.com>
" License:      Vim License (see `:help license`)
" Last Updated: Mon Dec 16 00:20:29 2019

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'cobalt3'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS'))

hi! link Character Constant
hi! link EndOfBuffer NonText
hi! link QuickFixLine Search
hi! link Boolean Constant
hi! link Conditional Statement
hi! link Define PreProc
hi! link Debug Special
hi! link Exception Statement
hi! link Float Number
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link Number Constant
hi! link PreCondit PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link Tag Special
hi! link Typedef Type

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#1C1C1C', '#902020', '#3AD900', '#FFC600',
        \ '#0088FF', '#967EFB', '#80FCFF', '#9E9E9E', '#626262', '#FF0000',
        \ '#3AD900', '#FFC600', '#00AAFF', '#FF628C', '#80FCFF', '#FFFFFF']
  hi Directory guifg=#668799 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=NONE guibg=#902020 guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#626262 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#9E9E9E guibg=#444444 guisp=NONE gui=italic cterm=italic
  hi MatchParen guifg=#FFFFFF guibg=#0050A4 guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi MoreMsg guifg=#88FF88 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#626262 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PMenu guifg=#CCCCCC guibg=#3A3A3A guisp=NONE gui=NONE cterm=NONE
  hi PMenuSel guifg=#3A3A3A guibg=#FFC600 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=#626262 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=#CCCCCC guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#3AD900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#FFFFFF guibg=#0088FF guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#FFFFFF guibg=#0088FF guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#444444 guibg=#1C1C1C guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=NONE guibg=NONE guisp=#FF0000 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap guifg=NONE guibg=NONE guisp=#00AAFF gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal guifg=NONE guibg=NONE guisp=#80FCFF gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare guifg=NONE guibg=NONE guisp=#967EFB gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi StatusLine guifg=#1C1C1C guibg=#CCCCCC guisp=NONE gui=italic cterm=italic
  hi StatusLineNC guifg=#FFFFFF guibg=#444444 guisp=NONE gui=italic cterm=italic
  hi TabLine guifg=#FFFFFF guibg=#3A3A3A guisp=NONE gui=underline cterm=underline
  hi TabLineFill guifg=#FFFFFF guibg=#9E9E9E guisp=NONE gui=underline cterm=underline
  hi TabLineSel guifg=#3A3A3A guibg=#FFC600 guisp=NONE gui=bold,underline cterm=bold,underline
  hi Title guifg=#3AD900 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi WarningMsg guifg=#902020 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#EB939A guibg=#3A3A3A guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#0088FF guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Constant guifg=#FF628C guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#3AD900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#FF9A00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#FFC600 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#FF9A00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#0088FF guibg=NONE guisp=NONE gui=italic cterm=italic
  hi PreProc guifg=#FF9A00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#FFC600 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#FF9A00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Structure guifg=#0088FF guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Special guifg=#88FF88 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#668799 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#668799 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi Ignore guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=NONE guibg=#902020 guisp=NONE gui=italic cterm=italic
  hi Todo guifg=NONE guibg=#0088FF guisp=NONE gui=italic cterm=italic
  hi ColorColumn guifg=NONE guibg=#020511 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guisp=NONE gui=NONE cterm=NONE
  hi Normal guifg=#FFFFFF guibg=#17252c guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=#3A3A3A guisp=NONE gui=NONE cterm=NONE
  hi CursorIM guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#3A3A3A guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#17252c guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#FFC600 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#626262 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=#626262 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#626262 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=#FFFFFF guibg=#0050A4 guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=NONE guisp=NONE gui=bold,underline ctermfg=NONE ctermbg=NONE cterm=bold,underline
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi StatusLine gui=NONE cterm=NONE
    hi StatusLineNC gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
    hi Operator gui=NONE cterm=NONE
    hi Structure gui=NONE cterm=NONE
    hi Error gui=NONE cterm=NONE
    hi Todo gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  hi Normal ctermfg=15 ctermbg=235 cterm=NONE
  if !has('patch-8.0.0616') " Fix for Vim bug
    set background=dark
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  hi Normal ctermfg=White ctermbg=Black cterm=NONE
  unlet s:t_Co s:italics
  finish
endif

" Color: black			      #1C1C1C                      234         Black 
" Color: darkest_grey			#3A3A3A                      237          Grey
" Color: darker_grey			#444444                      238          Grey
" Color: dark_grey			  #626262                      241          Grey
" Color: light_grey			  #9E9E9E                      247      DarkGrey 
" Color: lightest_grey		#CCCCCC                      252      DarkGrey
" Color: white			      #FFFFFF                       15         White
" Color: dark_orange			#FF9A00                      208    DarkYellow
" Color: yellow			      #FFC600                      220    DarkYellow
" Color: light_yellow			#F2ED7F                      228   LightYellow 
" Color: green			      #3AD900                       76         Green
" Color: light_green			#88FF88                      120    LightGreen 
" Color: purple			      #967EFB                      105   DarkMagenta 
" Color: darker_cobalt		#020511                      232         Black 
" Color: cobalt			      #17252c                      235         Black 
" Color: darker_blue			#0050A4                       25      DarkBlue 
" Color: dark_blue			  #0088FF                       33      DarkBlue
" Color: blue			        #00AAFF                       39          Blue 
" Color: light_blue			  #80FCFF                      123      DarkCyan 
" Color: dirty_blue			  #668799                       66     LightBlue
" Color: dark_red			    #902020                       88       DarkRed
" Color: red			        #FF0000                        9           Red 
" Color: dark_pink			  #FF628C                      204  LightMagenta 
" Color: dirty_pink			  #EB939A                      174  LightMagenta
" Term Colors: black dark_red green yellow dark_blue purple light_blue light_grey
" Term Colors: dark_grey red green yellow blue dark_pink light_blue white
" Background: dark
" vim: et ts=2 sw=2
