Directory: 'dirty_blue . .'
ErrorMsg: '. dark_red .'
VertSplit: 'dark_grey -'
Folded: 'light_grey darker_grey i'
MatchParen: 'white darker_blue .'
ModeMsg: ''
MoreMsg: 'light_green . .'
NonText: 'dark_grey - '
PMenu: 'lightest_grey darkest_grey .'
PMenuSel: 'darkest_grey yellow .'
PmenuSbar: 'dark_grey . .'
PmenuThumb: 'lightest_grey . .'
Question: 'green . .'
Search: 'white dark_blue .'
IncSearch: 'white dark_blue .'
SpecialKey: 'darker_grey black .'
SpellBad: 'white red'
SpellLocal: '. green u'
SpellCap: '. darker_blue u'
SpellRare: '. red u'
StatusLine: 'black lightest_grey i'
StatusLineNC: 'white darker_grey i'
TabLine: 'white darkest_grey u'
TabLineFill: 'white light_grey u'
TabLineSel: 'darkest_grey yellow bu'
Title: 'green . b'
WarningMsg: ''
WildMenu: 'dirty_pink darkest_grey .'
Comment: 'dark_blue . i'
Constant: 'dark_pink . .'
String: 'green . .'
Character: ''
Boolean: ''
Number: ''
Float: ''
Identifier: 'dark_orange . .'
Function: 'yellow . .'
Statement: 'dark_orange . .'
Conditional: ''
Repeat: ''
Label: ''
Operator: 'dark_blue . i'
Keyword: ''
Exception: ''
PreProc: 'dark_orange'
Include: ''
Define: ''
Macro: ''
PreCondit: ''
Type: 'yellow . .'
StorageClass: 'dark_orange . .'
Structure: 'dark_blue . i'
Typedef: ''
Special: 'light_green . .'
SpecialChar: ''
Tag: ''
Delimiter: 'dirty_blue . .'
StringDelimiter: 'dirty_blue . .'
SpecialComment: ''
Debug: ''
Underlined: ''
Ignore: ''
Error: '. dark_red i'
Todo: '. dark_blue i'
ColorColumn: '. darker_cobalt .'
Conceal: ''
Normal: 'white cobalt'
Cursor: '- darkest_grey .'
CursorIM: ''
CursorColumn: '. darkest_grey'
CursorLine: '. cobalt .'
CursorLineNr: 'dark_grey - .'
FoldColumn: 'dark_grey -'
SignColumn: 'dark_grey -'
LineNr: 'dark_grey -'
Visual: 'white darker_blue .'
VisualNOS: ''
